### ISSUE TITLE
No matching version found for @myriaddreamin/rehype-typst@0.5.0-rc9

### ISSUE THREAD

**Issue by OverflowCat** [Myriad-Dreamin/typst.ts#602]
The latest release of `@myriaddreamin/rehype-typst` is version "0.5.0-rc7", and version rc9 has not been published to npm.

Using an incompatible version with the compiler will result in:

```js
[
  {
    message: '`locate` with callback function is deprecated, hints: use a `context` expression instead',
    package: '',
    path: '/__main__.typ',
    range: { end: [Object], start: [Object] },
    severity: 2
  },
  {
    message: '`locate` with callback function is deprecated, hints: use a `context` expression instead',
    package: '',
    path: '/__main__.typ',
    range: { end: [Object], start: [Object] },
    severity: 2
  },
  {
    message: 'calling `state.final` with a location is deprecated, hints: try removing the location argument',
    package: '',
    path: '/__main__.typ',
    range: { end: [Object], start: [Object] },
    severity: 2
  },
  {
    message: 'calling `measure` with a styles argument is deprecated, hints: try removing the styles argument',
    package: '',
    path: '/__main__.typ',
    range: { end: [Object], start: [Object] },
    severity: 2
  },
  {
    message: '`style` is deprecated, hints: use a `context` expression instead',
    package: '',
    path: '/__main__.typ',
    range: { end: [Object], start: [Object] },
    severity: 2
  },
  {
    message: 'can only be used when context is known, hints: try wrapping this in a `context` expression, the `context` expression should wrap everything that depends on this function',
    package: '',
    path: '/__main__.typ',
    range: { end: [Object], start: [Object] },
    severity: 1
  },
  {
    message: 'while calling final',
    package: '',
    path: '/__main__.typ',
    range: { end: [Object], start: [Object] },
    severity: 4
  }
]
01:11:32 [ERROR] Spread syntax requires ...iterable[Symbol.iterator] to be a function
```

**Comment by Myriad-Dreamin** [comment]
I published them just now. Could you check it again?

**Comment by OverflowCat** [comment]
Still gets the same error using `"@myriaddreamin/rehype-typst": "0.5.0-rc9",` when rendering an empty $ block.

**Comment by Myriad-Dreamin** [comment]
perhaps same issue as #603

**Comment by kimhanm** [comment]
Looking at https://github.com/Myriad-Dreamin/typst.ts/blob/v0.5.1/projects/rehype-typst/lib/index.js, it seems that the patches to `lib/index.js` from #604 and #615 have not been included in the `0.5.0-rc9` to `0.5.1` tags.
These were only added merged into the main branch.
They aren't included in the `nightly/0.5.3`branches either.

**Comment by Myriad-Dreamin** [comment]
@OverflowCat is it working now?
